############################################################################################
# SmartIES Stack
############################################################################################
#
#     _______..___  ___.      ___      .______     .___________.   __   _______     _______.
#    /       ||   \/   |     /   \     |   _  \    |           |  |  | |   ____|   /       |
#   |   (----`|  \  /  |    /  ^  \    |  |_)  |   `---|  |----`  |  | |  |__     |   (----`
#    \   \    |  |\/|  |   /  /_\  \   |      /        |  |       |  | |   __|     \   \    
#.----)   |   |  |  |  |  /  _____  \  |  |\  \----.   |  |       |  | |  |____.----)   |   
#|_______/    |__|  |__| /__/     \__\ | _| `._____|   |__|       |__| |_______|_______/    
#                                                                                           
#                                                                                                                                                              
############################################################################################
version: "3.8"

services:
  node-red:
#    build: https://raw.githubusercontent.com/vilaj/IES/${VERSION}/stacks/SmartIES/Dockerfile-nodered
#    image: nodered:smartIES
    image: nodered/node-red:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1g
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - ${PORT10K}1880:1880
    networks:
      - net
    volumes:
      - node-red:/data
  grafana:    
    image: grafana/grafana:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4g
        reservations:
          cpus: '0.25'
          memory: 0.5g
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=agenty-flowcharting-panel,natel-discrete-panel,aidanmountford-html-panel,isaozler-paretochart-panel
      - GF_RENDERING_SERVER_URL=http://${HOST}:${PORT10K}8081/render
      - GF_RENDERING_CALLBACK_URL=http://${HOST}:${PORT10K}3000/
      - GF_SERVER_ROOT_URL=http://${HOST}:${PORT10K}3000/
      - GF_SERVER_ENABLE_GZIP=true
    ports:
      - ${PORT10K}3000:3000
    networks:
      - net
    volumes:
      - grafana-config:/etc/grafana/
      - grafana-data:/var/lib/grafana
  grafana-image-renderer:    
    image: grafana/grafana-image-renderer:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1g
    restart: unless-stopped
    ports:
      - ${PORT10K}8081:8081
    networks:
      - net
  MQTT: 
    build: https://raw.githubusercontent.com/vilaj/IES/${VERSION}/stacks/SmartIES/Dockerfile-mosquitto
    image: mosquitto:smartIES 
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1g
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - ${PORT10K}1883:1883
      - ${PORT10K}8883:8883
      - ${PORT10K}9001:9001
  timescaleDB:    
    image: timescale/timescaledb:latest-pg12
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 5g
        reservations:
          cpus: '0.50'
          memory: 2g
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${PORT10K}5432:5432
    networks:
      - net
    volumes:
      - timescaledb-data:/var/lib/postgresql/data   
  pgadmin:    
    image: dpage/pgadmin4:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4g
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${PORT10K}2080:80
    networks:
      - net 
volumes:
  node-red:
    name: node-red${PORT10K}
  grafana-config:
    name: grafana-config${PORT10K}
  grafana-data:
    name: grafana-data${PORT10K}
  timescaledb-data:
    name: timescaledb-data${PORT10K}

networks:
  net:
