# syntax=docker/dockerfile:1
FROM eclipse-mosquitto:1.6.15
ADD https://raw.githubusercontent.com/vilaj/IES/${VERSION}/stacks/SmartIES/mosquitto-settings.conf /mosquitto/config/mosquitto.conf
ADD https://raw.githubusercontent.com/vilaj/IES/${VERSION}/stacks/SmartIES/mosquitto-passwd /etc/mosquitto/passwd
