################################################################################
# SmartIES Stack or Compose
################################################################################
# 
# 
################################################################################
version: "3.7"

services:
  node-red:
    build: https://raw.githubusercontent.com/vilaj/IES/main/stacks/SmartIES/Dockerfile-nodered
    image: nodered:smartIES
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - 31880:1880
    networks:
      - net
    volumes:
      - node-red:/data
  grafana:    
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=agenty-flowcharting-panel,natel-discrete-panel,aidanmountford-html-panel,isaozler-paretochart-panel
    ports:
      - 33000:3000
    networks:
      - net
    volumes:
      - grafana-config:/etc/grafana/
      - grafana-data:/var/lib/grafana
  MQTT: 
    build: https://raw.githubusercontent.com/vilaj/IES/main/stacks/SmartIES/Dockerfile-mosquitto
    image: mosquitto:smartIES
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - 31883:1883
      - 38883:8883
      - 39001:9001
  timescaleDB:    
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=timescaleDB
    ports:
      - 35432:5432
    networks:
      - net
    volumes:
      - timescaledb-data:/var/lib/postgresql/data      
volumes:
  node-red:
  grafana-config:
  grafana-data:
  mosquitto_data:
  timescaledb-data:

networks:
  net:
