# syntax=docker/dockerfile:1
FROM nginx:latest
RUN curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash 
# SHELL ["/bin/bash", "-c"]
# RUN filebrowser -p 8080 -a filebrowser -r /usr/share/nginx/html
