################################################################################
# SmartIES Stack or Compose
################################################################################
# 
# 
################################################################################
version: "3.7"

services:
  node-red:
    build: https://raw.githubusercontent.com/vilaj/IES/main/stacks/SmartIES/Dockerfile-nodered
    image: nodered:smartIES
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4g
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - 31880:1880
    networks:
      - net
    volumes:
      - node-red:/data
  grafana:    
    image: grafana/grafana:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4000M
        reservations:
          cpus: '0.10'
          memory: 1g
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=agenty-flowcharting-panel,natel-discrete-panel,aidanmountford-html-panel,isaozler-paretochart-panel
    ports:
      - 33000:3000
    networks:
      - net
    volumes:
      - grafana-config:/etc/grafana/
      - grafana-data:/var/lib/grafana
  grafana-image-renderer:    
    image: grafana/grafana-image-renderer:latest
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 1g
    restart: unless-stopped
    ports:
      - 38081:8081
    networks:
      - net
  MQTT: 
    build: https://raw.githubusercontent.com/vilaj/IES/main/stacks/SmartIES/Dockerfile-mosquitto
    image: mosquitto:smartIES 
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 1g
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - 31883:1883
      - 38883:8883
      - 39001:9001
  timescaleDB:    
    image: timescale/timescaledb:latest-pg12
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 5g
        reservations:
          cpus: '0.25'
          memory: 2g
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=timescaleDB
    ports:
      - 35432:5432
    networks:
      - net
    volumes:
      - timescaledb-data:/var/lib/postgresql/data   
  pgadmin:    
    image: dpage/pgadmin4:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4g
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=jaume.vila@installux-es.com
      - PGADMIN_DEFAULT_PASSWORD=timescaleDB
    ports:
      - 32080:80
    networks:
      - net 
volumes:
  node-red:
  grafana-config:
  grafana-data:
  mosquitto_data:
  timescaledb-data:

networks:
  net:
