################################################################################
# SmartIES Stack or Compose
################################################################################
# 
# 
################################################################################
version: "3.7"

services:
  node-red:
    build: https://raw.githubusercontent.com/vilaj/IES/main/stacks/SmartIES/Dokerfile-nodered
    image: nodered:smartIES
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 31880:1880
    networks:
      - net
    volumes:
      - /var/lib/docker/volumes/smarties_vol/_data/node-red:/data
  grafana:    
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=agenty-flowcharting-panel,natel-discrete-panel,aidanmountford-html-panel,isaozler-paretochart-panel
    ports:
      - 33000:3000
    networks:
      - net
    volumes:
      - /var/lib/docker/volumes/smarties_vol/_data/grafana/config:/etc/grafana/
      - /var/lib/docker/volumes/smarties_vol/_data/grafana/data:/var/lib/grafana
volumes:
  vol:

networks:
  net:
